POST http://localhost:8080/api/members/signup
Content-Type: application/json

{
  "email": "wonbin@mail.com",
  "nickName": "member",
  "password": "bin1234!",
  "passwordCheck" : "bin1234!"
}

###
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email": "wonbin@mail.com",
  "password": "bin1234!"
}
